### ISSUE TITLE
Todo list for the final report

### ISSUE THREAD

**Issue by oneturkmen** [oneturkmen/rust-jit#6]
The following is a list of tasks to be performed **in sequence**:
- [x] Move Figure 4 into previous page.
- [x] Perform another pass over the report to identify any grammatical errors; if certain sentences can be improved; missing or redundant information; etc.
- [x] Add citations.
- [x] Perform another pass to make sure everything looks good, structure is OK, nothing is missing, etc.
